theme: jekyll-theme-midnight
logo: https://micheelengronne.github.io/micheelengronne/logo.png
title: Michée Lengronne
description: From a double formation of IT project engineer and manager, I have a specialty in IT security and opensource world.
