theme: jekyll-theme-midnight
logo: https://micheelengronne.github.io/micheelengronne/logo.png
title: Michée Lengronne
description: Transforming your infrastructures and data to 0-trust, on-premise cloud-native data platforms by engineering and architecture.
